### ISSUE TITLE
Dependency versions

### ISSUE THREAD

**Issue by joepie91** [aumberg/morsetick#1]
Currently, the dependencies look like this:

``` json
    "dependencies": {
        "wav": "*",
        "lame": "*",
        "jsdom": "3.1.2",
        "bhttp": "*",
        "speaker": "*",
        "keypress": "*"
    },
```

However, `*` will allow an upgrade to a version that is not backwards-compatible (due to semantic versioning), and might unexpectedly result in failure of the module. The correct way is to use the format `^1.2.3`, where `1.2.3` is the tested version - this will allow any 1.x.x version starting from 1.2.3.

Alternatively, when installing dependencies using `npm install --save` or `npm install --save-dev`, the version specifications are automatically configured like this.

**Comment by aumberg** [comment]
Repaired. Big thanks Sven for yours good library - <b>bhttp</b> !
